# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gY_15Ydt_vVYamU24-RsgJ4-GxXAKi4f
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
print("All libraries imported successfully!")

data = pd.read_csv("SuperMarket Analysis.csv")
print(data.head())

data.info()

data.describe()

data.describe(include='object')

data.duplicated().sum()

data.isnull().sum()

data.groupby('Product line')['Sales'].sum().sort_values(ascending=False)

product_sales = data.groupby('Product line')['Sales'].sum().sort_values(ascending=False)
print(product_sales)

product_sales.idxmax()

product_sales.max

import matplotlib.pyplot as plt
product_sales = data.groupby('Product line')['Sales'].sum().sort_values(ascending=False)
plt.figure(figsize=(10, 6))
product_sales.plot(kind='bar')
plt.title('Total Sales by Product Lines')
plt.xlabel('Product Line')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

city_sales = data.groupby('City')['Sales'].sum().sort_values(ascending=False)
print(city_sales)

payment_counts = data['Payment'].value_counts()
print(payment_counts)

payment_counts = data['Payment'].value_counts()

plt.figure(figsize=(8, 5))

payment_counts.plot(kind='bar')

plt.title('Most Popular Payment Methods')
plt.xlabel('Payment Method')
plt.ylabel('Number of Transactions')

plt.xticks(rotation=0)

plt.tight_layout()

plt.show()

gender_sales = data.groupby('Gender')['Sales'].sum().sort_values(ascending=False)

print(gender_sales)

gender_sales = data.groupby('Gender')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(6, 5))

gender_sales.plot(kind='bar')

plt.title('Total Sales by Gender')
plt.xlabel('Gender')
plt.ylabel('Total Sales')

plt.xticks(rotation=0)

plt.tight_layout()

plt.show()

customer_sales = data.groupby('Customer type')['Sales'].sum().sort_values(ascending=False)

print(customer_sales)

customer_sales = data.groupby('Customer type')['Sales'].sum().sort_values(ascending=False)

plt.figure(figsize=(6, 5))

customer_sales.plot(kind='bar')

plt.title('Total Sales by Customer Type')
plt.xlabel('Customer Type')
plt.ylabel('Total Sales')

plt.xticks(rotation=0)

plt.tight_layout()

plt.show()

numeric_data = data.select_dtypes(include='number')

correlation = numeric_data.corr()

plt.figure(figsize=(10, 8))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Between Numerical Variables')

plt.show()

# ==========================================
# CODEALPHA DATA VISUALIZATION PROJECT
# Supermarket Sales Analysis
# ==========================================


# 1. Import Libraries
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


# 2. Load Dataset
data = pd.read_csv("SuperMarket Analysis.csv")


# 3. Explore the Dataset
print("First 5 Rows:")
print(data.head())

print("\nDataset Information:")
data.info()

print("\nStatistical Summary:")
print(data.describe())

print("\nMissing Values:")
print(data.isnull().sum())

print("\nDuplicate Rows:")
print(data.duplicated().sum())


# 4. Sales by Product Line
product_sales = data.groupby('Product line')['Sales'].sum().sort_values(ascending=False)

print("\nSales by Product Line:")
print(product_sales)

plt.figure(figsize=(10, 6))
product_sales.plot(kind='bar')

plt.title('Total Sales by Product Line')
plt.xlabel('Product Line')
plt.ylabel('Total Sales')
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()


# 5. Sales by City
city_sales = data.groupby('City')['Sales'].sum().sort_values(ascending=False)

print("\nSales by City:")
print(city_sales)

plt.figure(figsize=(8, 5))
city_sales.plot(kind='bar')

plt.title('Total Sales by City')
plt.xlabel('City')
plt.ylabel('Total Sales')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()


# 6. Payment Method Analysis
payment_counts = data['Payment'].value_counts()

print("\nPayment Method Usage:")
print(payment_counts)

plt.figure(figsize=(8, 5))
payment_counts.plot(kind='bar')

plt.title('Most Popular Payment Methods')
plt.xlabel('Payment Method')
plt.ylabel('Number of Transactions')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()


# 7. Gender-wise Sales
gender_sales = data.groupby('Gender')['Sales'].sum().sort_values(ascending=False)

print("\nSales by Gender:")
print(gender_sales)

plt.figure(figsize=(6, 5))
gender_sales.plot(kind='bar')

plt.title('Total Sales by Gender')
plt.xlabel('Gender')
plt.ylabel('Total Sales')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()


# 8. Customer Type Analysis
customer_sales = data.groupby('Customer type')['Sales'].sum().sort_values(ascending=False)

print("\nSales by Customer Type:")
print(customer_sales)

plt.figure(figsize=(6, 5))
customer_sales.plot(kind='bar')

plt.title('Total Sales by Customer Type')
plt.xlabel('Customer Type')
plt.ylabel('Total Sales')
plt.xticks(rotation=0)
plt.tight_layout()
plt.show()


# 9. Correlation Heatmap
numeric_data = data.select_dtypes(include='number')

correlation = numeric_data.corr()

plt.figure(figsize=(10, 8))

sns.heatmap(
    correlation,
    annot=True,
    cmap='coolwarm'
)

plt.title('Correlation Between Numerical Variables')
plt.show()

print("Supermarket Sales Analysis Project")